### ISSUE TITLE
Steps made too complex for no reason

### ISSUE THREAD

**Issue by roshair** [mspnp/aks-baseline-multi-region#69]
The steps are made too complex by using GitHub pipeline, flux and all the fancy tooling. It is too difficult to follow. Honestly, i have been trying to following this in multiple attempts, but i can't even deploy at step 6, to deploy AKS clusters because of so much of tooling. Can you simplify the examples or create a video guide as to how to follow this stuff?

**Comment by ckittel** [comment]
This is great feedback @roshair.  And yeah, it's really complicated with the injection of the GitHub pipeline orchestrating part of the deployment.  When we designed this, we thought about skipping it and just making an "easy button" for deployment -- but then we got feedback that said, "No, you need to teach that orchestrating this this part of the solution, and not something someone needs to fit in later."  The purpose of this reference implementation is NOT to teach the fundamentals of AKS, that you'll find in the [AKS baseline](https://github.com/mspnp/aks-baseline) and the ALZ implementations as well.  It's instead to put a flashlight on the complexities of a fleet of clusters, and those complexities are in fact one of the learning objectives of this walk through.

Which leads to the "examples or create a video guide" suggest.  I love that idea.  We are currently not staffed to add any additional items that would cause more maintenance effort on this reference implementation, such as maintaining video or text-based examples.  We've had contributors volunteer things like this in the past though!  As a MSFT employee, if you'd like to help contribute to this repo to make it more consumable, I'd love to collaborate with you.  Ping me on teams.
